### ISSUE TITLE
Equation mistakes in `text.pdf`

### ISSUE THREAD

**Issue by m12watanabe1a** [NaokiAkai/AutoNaviSim#1]
In `text.pdf` page 2, the equation is described as followings,

$$
\theta_p = \tan^{-1} \left( \frac{y_t}{x_t} \right) + \textcolor{Red}{\frac{R}{l}} + \frac{\pi}{2}
$$

However, I think it should be

$$
\theta_p = \tan^{-1} \left( \frac{y_t}{x_t} \right) + \textcolor{Red}{\frac{l}{R}} + \frac{\pi}{2}
$$

The equation described in the code follows the right one.
https://github.com/NaokiAkai/AutoNaviSim/blob/main/src/circle_follow/main.cpp#L76

**Comment by NaokiAkai** [comment]
Thank you for pointing out it. Your comment is correct. I have revised text.pdf.
